export const diasOptions = [
  { value: "0-5", label: "0 a 5 dias" },
  { value: "6-10", label: "6 a 10 dias" },
  { value: "11-14", label: "11 a 14 dias" },
  {
    value: "mais-2-semanas",
    label: "Há mais de duas semanas, mas nas últimas quatro semanas",
  },
  { value: "mais-4-semanas", label: "Há mais de 4 semanas" },
];

export const interesseOpcoes = [
  "Manter a massa muscular enquanto perco peso",
  "Preferiria não injetar",
  "Gerenciar possíveis efeitos colaterais, como náuseas/vômitos",
  "Auxiliar no processo de envelhecimento e a promoção da longevidade (danos celulares/ao DNA, disfunções do sistema imunológico, etc)",
  "Melhora da função cognitiva e da clareza mental",
  "Melhorar os níveis de energia",
  "Regulação da menstruação e do estado hormonal",
  "Melhorar a qualidade do sono",
  "Não tenho certeza — gostaria de discutir as opções de formulação com um profissional clínico por meio de uma consulta virtual ao vivo",
];

export const estadosBrasil = [
  { sigla: "AC", nome: "Acre" },
  { sigla: "AL", nome: "Alagoas" },
  { sigla: "AP", nome: "Amapá" },
  { sigla: "AM", nome: "Amazonas" },
  { sigla: "BA", nome: "Bahia" },
  { sigla: "CE", nome: "Ceará" },
  { sigla: "DF", nome: "Distrito Federal" },
  { sigla: "ES", nome: "Espírito Santo" },
  { sigla: "GO", nome: "Goiás" },
  { sigla: "MA", nome: "Maranhão" },
  { sigla: "MT", nome: "Mato Grosso" },
  { sigla: "MS", nome: "Mato Grosso do Sul" },
  { sigla: "MG", nome: "Minas Gerais" },
  { sigla: "PA", nome: "Pará" },
  { sigla: "PB", nome: "Paraíba" },
  { sigla: "PR", nome: "Paraná" },
  { sigla: "PE", nome: "Pernambuco" },
  { sigla: "PI", nome: "Piauí" },
  { sigla: "RJ", nome: "Rio de Janeiro" },
  { sigla: "RN", nome: "Rio Grande do Norte" },
  { sigla: "RS", nome: "Rio Grande do Sul" },
  { sigla: "RO", nome: "Rondônia" },
  { sigla: "RR", nome: "Roraima" },
  { sigla: "SC", nome: "Santa Catarina" },
  { sigla: "SP", nome: "São Paulo" },
  { sigla: "SE", nome: "Sergipe" },
  { sigla: "TO", nome: "Tocantins" },
];
